### ISSUE TITLE
error when steps in " Plot adjusted nucleotide frequencies"

### ISSUE THREAD

**Issue by lynnyummy** [txje/sequence-bias-adjustment#1]
Hi, I am using sequence-bias-adjustment to shift the sequence bias of my ATAC-seq data, it runs quite good in the first few steps, but it has the error when it comes to the step "Plot adjusted nucleotide frequencies".
Would you please help me to figure out what happened? 
Thank you!

[20200602131257] start: Plot adjusted nucleotide frequencies
Traceback (most recent call last):
  File "plot_csv.py", line 76, in <module>
    main(args.csv, out, args.log if args.log != None else 0, args.xmin, args.xmax, args.smooth, (w,h), args.stacked)
  File "plot_csv.py", line 33, in main
    fig = figure(figsize=(s/100.0 for s in size), dpi=100)
  File "/data/home/myaccount/miniconda3/envs/bio/lib/python2.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/data/home/myaccount/miniconda3/envs/bio/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 160, in new_figure_manager
    fig = fig_cls(*args, **kwargs)
  File "/data/home/myaccount/miniconda3/envs/bio/lib/python2.7/site-packages/matplotlib/figure.py", line 356, in __init__
    if not np.isfinite(figsize).all():
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by txje** [comment]
So that I can try to recreate this error, can you let me know what version of python (I see it's some variant of 2.7) and numpy you are using, and the command you used that resulted in the error. If you tried to specify the figure size explicitly like "... --size 800x600" with invalid numerical values, it could have caused an issue.

**Comment by lynnyummy** [comment]
> So that I can try to recreate this error, can you let me know what version of python (I see it's some variant of 2.7) and numpy you are using, and the command you used that resulted in the error. If you tried to specify the figure size explicitly like "... --size 800x600" with invalid numerical values, it could have caused an issue.

Hi, thanks for replying!

I use the Python 2.7.18 and numpy 1.16.6. I updated the numpy yesterday when I meet this issue, then I ran it again but today still meet the same problem. 
I think I didn't specify any figure size, they maybe all default.

Thank you so much for the kind helps!

**Comment by txje** [comment]
Thanks. I found the likely problem, please see if commit  a771f7c fixes your problem. This repo has not been maintained - this incompatibility seems to have appeared somewhere between numpy 1.11 and 1.13.

**Comment by lynnyummy** [comment]
> Thanks. I found the likely problem, please see if commit [a771f7c](https://github.com/txje/sequence-bias-adjustment/commit/a771f7c56397981dfdad0a96f94254efd102260b) fixes your problem. This repo has not been maintained - this incompatibility seems to have appeared somewhere between numpy 1.11 and 1.13.

Thanks for your clarification! I downgraded NumPy to 1.12.1, and ran it again, hope this time will work well!
Thank you very much!

**Comment by txje** [comment]
No, just pull master and it should work in any version of numpy

**Comment by lynnyummy** [comment]
> No, just pull master and it should work in any version of numpy
> […](#)
> On Jun 3, 2020, at 5:59 PM, lynnyummy ***@***.***> wrote: ﻿ Thanks. I found the likely problem, please see if commit [a771f7c](https://github.com/txje/sequence-bias-adjustment/commit/a771f7c56397981dfdad0a96f94254efd102260b) fixes your problem. This repo has not been maintained - this incompatibility seems to have appeared somewhere between numpy 1.11 and 1.13. Thanks for your clarification! I downgraded NumPy to 1.12.1, and ran it again, hope this time will work well! Thank you very much! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Sorry, I don't understand the meaning of "pull master "? Could you please explain what should I do for the proper resolution? Thank you!

**Comment by txje** [comment]
I updated the code - get the updated version however you did the first time and try running it again

**Comment by lynnyummy** [comment]
> I updated the code - get the updated version however you did the first time and try running it again
> […](#)
> On Jun 3, 2020, at 6:57 PM, lynnyummy ***@***.***> wrote: ﻿ No, just pull master and it should work in any version of numpy … On Jun 3, 2020, at 5:59 PM, lynnyummy @.***> wrote: ﻿ Thanks. I found the likely problem, please see if commit [a771f7c](https://github.com/txje/sequence-bias-adjustment/commit/a771f7c56397981dfdad0a96f94254efd102260b) fixes your problem. This repo has not been maintained - this incompatibility seems to have appeared somewhere between numpy 1.11 and 1.13. Thanks for your clarification! I downgraded NumPy to 1.12.1, and ran it again, hope this time will work well! Thank you very much! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Sorry, I don't understand the meaning of "pull master "? Could you please explain what should I do for the proper resolution? Thank you! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Ah, OK! Thank you for your help! Now they are running, hope this time they will be fine! Thanks!

**Comment by lynnyummy** [comment]
> Thanks. I found the likely problem, please see if commit [a771f7c](https://github.com/txje/sequence-bias-adjustment/commit/a771f7c56397981dfdad0a96f94254efd102260b) fixes your problem. This repo has not been maintained - this incompatibility seems to have appeared somewhere between numpy 1.11 and 1.13.

Hi, I downgraded numpy to 1.12.1, but still meet the same issue. Should I download and install sequence-bias-adjustment again?

**Comment by txje** [comment]
Yes

**Comment by lynnyummy** [comment]
> Yes
> […](#)

Sure, I have done these, hope this time could get the results! Thanks!
