### ISSUE TITLE
The k value for ATAC-seq reads shifting

### ISSUE THREAD

**Issue by lynnyummy** [txje/sequence-bias-adjustment#2]
Hi Jeremy,

I have new issue with the the k value for ATACseq data. The manual suggests we use 5 for shifting, but for the ATAC-seq file I got, seems after reads shifting, the called peaks changed in an unreasonable way, such as I can call much much more (or less) peaks from the shifted bam than from the non-shifted bam.  

I think there could be something I need to refine with the k value, Do you have any suggestion? I read from bedtools, for the ATAC shift, it defines 4,-5 or 5,-4. I don't know if I can also use this in sequence-bias-adjustment command? 

Thanks for you helps very much!

Best wishes,
Lynn

**Comment by txje** [comment]
The k parameter is not the offset, it's the size of the tiles used to identify and correct the bias, so theoretically it shouldn't matter where the read start is relative to the bias profile as long as it's within the 25bp margin on either side of the read's alignment start site. In the paper, we showed some encouraging results on ATAC data, but I can't say for sure why you're getting weird results. ATAC has a strong bias signature so in principle it's not surprising to see many more or many fewer peaks after bias correction.

**Comment by lynnyummy** [comment]
> The k parameter is not the offset, it's the size of the tiles used to identify and correct the bias, so theoretically it shouldn't matter where the read start is relative to the bias profile as long as it's within the 25bp margin on either side of the read's alignment start site. In the paper, we showed some encouraging results on ATAC data, but I can't say for sure why you're getting weird results. ATAC has a strong bias signature so in principle it's not surprising to see many more or many fewer peaks after bias correction.

Thanks for the explanation! Yes I also found the k parameter doesn't mean the shifting offset. I will just process my data without the adjustment. Thank you very much!
